version: '3.8'

services:

  db:
    image: postgres
    container_name: skillflix-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: skillflix_db


